USE [ENCUESTA]
GO
/****** Object:  Table [dbo].[FECHA]    Script Date: 21/11/2022 19:44:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FECHA](
	[DIA] [int] NULL,
	[MES] [int] NULL,
	[ANIO] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 21/11/2022 19:44:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[IDPERSONA] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[EDAD] [int] NOT NULL,
	[GENERO] [varchar](10) NULL,
 CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED 
(
	[IDPERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESPUESTA]    Script Date: 21/11/2022 19:44:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESPUESTA](
	[IDREPUESTA] [int] IDENTITY(1,1) NOT NULL,
	[IDPERSONA] [int] NULL,
	[RESPUESTA1] [char](1) NOT NULL,
	[RESPUESTA2] [char](1) NOT NULL,
 CONSTRAINT [PK_IDRESPUESTA] PRIMARY KEY CLUSTERED 
(
	[IDREPUESTA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RESPUESTA]  WITH CHECK ADD  CONSTRAINT [FK_IDPERSONA] FOREIGN KEY([IDPERSONA])
REFERENCES [dbo].[PERSONA] ([IDPERSONA])
GO
ALTER TABLE [dbo].[RESPUESTA] CHECK CONSTRAINT [FK_IDPERSONA]
GO
